/**
 * Draft Generator Tests — FlowV2 → XCUITest/Appium test code drafts.
 *
 * US-20.1: Test code draft generation from FlowV2 objects.
 *
 * AC1: Generate XCUITest / Appium test code drafts from Flow.
 * AC2: Draft marked as DRAFT, experimental.
 * AC3: Default output to ~/.itestagent/runs/<run_id>/drafts/.
 * AC4: Never auto-commit; user confirms before copying to project.
 */
import { describe, expect, it } from 'bun:test';
import { generateDraft } from '../src/draft-generator.js';
import type { FlowV2 } from '../src/schema.js';

// ─── Test Fixtures ────────────────────────────────────────────────

function makeBasicTapFlow(overrides: Partial<FlowV2> = {}): FlowV2 {
  return {
    schemaVersion: 'itestagent.flow.v2' as const,
    flowId: 'login-smoke-test',
    source: 'agent-recorded',
    status: 'draft',
    supportedTargetKinds: ['simulator'],
    requiredCapabilities: ['appium-wda'],
    lastValidatedTargets: [{ kind: 'simulator', udid: 'TEST-UDID' }],
    steps: [
      {
        action: 'launchApp',
        target: 'com.example.app',
      },
      {
        action: 'tap',
        target: 'Login button',
        locator: { strategy: 'identifier', value: 'login_btn' },
      },
      {
        action: 'wait',
        durationMs: 1000,
      },
    ],
    ...overrides,
  };
}

function makeAll18ActionsFlow(): FlowV2 {
  return {
    schemaVersion: 'itestagent.flow.v2' as const,
    flowId: 'all-actions-test',
    source: 'agent-recorded',
    status: 'draft',
    supportedTargetKinds: ['simulator'],
    requiredCapabilities: ['appium-wda'],
    lastValidatedTargets: [{ kind: 'simulator', udid: 'TEST-UDID' }],
    steps: [
      { action: 'launchApp', target: 'com.example.app' },
      { action: 'terminateApp', target: 'com.example.app' },
      { action: 'tap', target: 'Button', locator: { strategy: 'identifier', value: 'my_btn' } },
      {
        action: 'longPress',
        target: 'Hold',
        locator: { strategy: 'identifier', value: 'hold_btn' },
        durationMs: 2000,
      },
      { action: 'swipe', target: 'List', direction: 'up' },
      {
        action: 'typeText',
        target: 'Email',
        locator: { strategy: 'identifier', value: 'email_field' },
        value: 'test@test.com',
      },
      { action: 'pressButton', target: 'Home', value: 'home' },
      { action: 'openUrl', target: 'Browser', value: 'https://example.com' },
      { action: 'screenshot', target: 'Screen capture' },
      { action: 'getUiTree', target: 'Dump UI' },
      { action: 'startRecording', target: 'Start video' },
      { action: 'stopRecording', target: 'Stop video' },
      { action: 'collectLogs', target: 'System logs' },
      {
        action: 'assertVisible',
        target: 'Login',
        locator: { strategy: 'identifier', value: 'login_btn' },
      },
      {
        action: 'assertNotVisible',
        target: 'Error',
        locator: { strategy: 'identifier', value: 'error_msg' },
      },
      {
        action: 'assertText',
        target: 'Title',
        locator: { strategy: 'identifier', value: 'title_lbl' },
        expectedText: 'Welcome',
      },
      { action: 'wait', durationMs: 500 },
      { action: 'comment', comment: 'End of smoke test' },
    ],
  };
}

// ─── Test 1: XCUITest generation with basic tap flow ──────────────

describe('generateDraft — XCUITest', () => {
  it('generates XCUITest class with header, setUp, tearDown, and test method', () => {
    const flow = makeBasicTapFlow();
    const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-001' });

    // Header
    expect(result.code).toContain('⚠️  DRAFT — EXPERIMENTAL');
    expect(result.code).toContain('Generated by iTestAgent');
    expect(result.code).toContain('Generated from Flow: login-smoke-test');
    expect(result.code).toContain('Run ID: run-001');

    // Core XCUITest imports and class
    expect(result.code).toContain('import XCTest');
    expect(result.code).toContain('XCTestCase');
    expect(result.code).toContain('LoginSmokeTestTests');
    expect(result.code).toContain('func setUp');
    expect(result.code).toContain('func tearDown');
    expect(result.code).toContain('func test');

    // Language and metadata
    expect(result.language).toBe('swift');
    expect(result.flowId).toBe('login-smoke-test');
    expect(result.runId).toBe('run-001');

    // Steps mapped
    expect(result.code).toContain('launch()');
    expect(result.code).toContain('login_btn');
    expect(result.code).toContain('sleep');
  });
});

// ─── Test 2: Appium generation with basic tap flow ─────────────────

describe('generateDraft — Appium', () => {
  it('generates Appium describe/it block with header, before, after hooks', () => {
    const flow = makeBasicTapFlow();
    const result = generateDraft(flow, { format: 'appium', runId: 'run-002' });

    // Header
    expect(result.code).toContain('⚠️  DRAFT — EXPERIMENTAL');
    expect(result.code).toContain('Generated by iTestAgent');
    expect(result.code).toContain('Generated from Flow: login-smoke-test');
    expect(result.code).toContain('Run ID: run-002');

    // Core Appium / WDIO imports and structure
    expect(result.code).toContain('import { remote }');
    expect(result.code).toContain('webdriverio');
    expect(result.code).toContain('describe');
    expect(result.code).toContain("describe('LoginSmokeTest'");
    expect(result.code).toContain('before(async');
    expect(result.code).toContain('after(async');

    // Language and metadata
    expect(result.language).toBe('typescript');
    expect(result.flowId).toBe('login-smoke-test');
    expect(result.runId).toBe('run-002');

    // Steps mapped
    expect(result.code).toContain("activateApp('com.example.app')");
    expect(result.code).toContain('login_btn');
    expect(result.code).toContain('pause');
  });
});

// ─── Test 3: File path format ─────────────────────────────────────

describe('generateDraft — filePath', () => {
  it('generates correct XCUITest .swift file path', () => {
    const flow = makeBasicTapFlow();
    const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-003' });

    expect(result.filePath).toContain('.itestagent/runs/run-003/drafts');
    expect(result.filePath).toContain('login-smoke-test.swift');
    expect(result.filePath).toMatch(
      /\.itestagent\/runs\/run-003\/drafts\/login-smoke-test\.swift$/,
    );
  });

  it('generates correct Appium .test.ts file path', () => {
    const flow = makeBasicTapFlow();
    const result = generateDraft(flow, { format: 'appium', runId: 'run-004' });

    expect(result.filePath).toContain('.itestagent/runs/run-004/drafts');
    expect(result.filePath).toContain('login-smoke-test.test.ts');
    expect(result.filePath).toMatch(
      /\.itestagent\/runs\/run-004\/drafts\/login-smoke-test\.test\.ts$/,
    );
  });
});

// ─── Test 4: All 18 actions are mapped ─────────────────────────────

describe('generateDraft — all 18 actions', () => {
  it('maps every action to XCUITest code', () => {
    const flow = makeAll18ActionsFlow();
    const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-005' });

    // Every action should produce at least one line of code
    // launchApp / terminateApp
    expect(result.code).toContain('launch()');
    expect(result.code).toContain('terminate()');
    // tap with locator
    expect(result.code).toContain('my_btn');
    // longPress
    expect(result.code).toContain('press(forDuration');
    // swipe
    expect(result.code).toContain('swipeUp');
    // typeText
    expect(result.code).toContain('typeText');
    expect(result.code).toContain('test@test.com');
    // pressButton
    expect(result.code).toContain('.home');
    // openUrl
    expect(result.code).toContain('mobilesafari');
    // screenshot
    expect(result.code).toContain('screenshot()');
    // getUiTree
    expect(result.code).toContain('debugDescription');
    // startRecording / stopRecording
    expect(result.code).toContain('DRAFT: screen recording');
    // collectLogs
    expect(result.code).toContain('DRAFT: log collection');
    // assertVisible
    expect(result.code).toContain('XCTAssertTrue');
    // assertNotVisible
    expect(result.code).toContain('XCTAssertFalse');
    // assertText
    expect(result.code).toContain('XCTAssertEqual');
    expect(result.code).toContain('Welcome');
    // wait
    expect(result.code).toContain('sleep(0');
    // comment
    expect(result.code).toContain('// End of smoke test');
  });

  it('maps every action to Appium code', () => {
    const flow = makeAll18ActionsFlow();
    const result = generateDraft(flow, { format: 'appium', runId: 'run-006' });

    // launchApp / terminateApp
    expect(result.code).toContain("activateApp('com.example.app')");
    expect(result.code).toContain("terminateApp('com.example.app')");
    // tap with locator
    expect(result.code).toContain('my_btn');
    expect(result.code).toContain('click()');
    // longPress
    expect(result.code).toContain('2000');
    // swipe
    expect(result.code).toContain("'mobile: swipe'");
    // typeText
    expect(result.code).toContain('setValue');
    expect(result.code).toContain('test@test.com');
    // pressButton
    expect(result.code).toContain('pressDeviceKey');
    // openUrl
    expect(result.code).toContain("driver.url('https://example.com')");
    // screenshot
    expect(result.code).toContain('takeScreenshot()');
    // getUiTree
    expect(result.code).toContain('getPageSource()');
    // startRecording / stopRecording
    expect(result.code).toContain('startRecordingScreen()');
    expect(result.code).toContain('stopRecordingScreen()');
    // collectLogs
    expect(result.code).toContain("getLogs('syslog')");
    // assertVisible
    expect(result.code).toContain('toBeDisplayed()');
    // assertNotVisible
    expect(result.code).toContain('not.toBeDisplayed()');
    // assertText
    expect(result.code).toContain("toHaveText('Welcome')");
    // wait
    expect(result.code).toContain('pause(500)');
    // comment
    expect(result.code).toContain('// End of smoke test');
  });
});

// ─── Test 5: Missing locator generates placeholder comment (R5) ────

describe('generateDraft — missing locator (R5)', () => {
  it('generates placeholder when locator is missing in XCUITest', () => {
    const flow = makeBasicTapFlow({
      steps: [{ action: 'tap', target: 'Mystery Button' }],
    });
    const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-007' });

    expect(result.code).toContain('DRAFT: locator missing');
    expect(result.code).toContain('Mystery Button');
  });

  it('generates placeholder when locator is missing in Appium', () => {
    const flow = makeBasicTapFlow({
      steps: [{ action: 'tap', target: 'Mystery Button' }],
    });
    const result = generateDraft(flow, { format: 'appium', runId: 'run-008' });

    expect(result.code).toContain('DRAFT: locator missing');
    expect(result.code).toContain('Mystery Button');
  });

  it('never fabricates a locator value when locator is undefined (R5)', () => {
    const flow = makeBasicTapFlow({
      steps: [{ action: 'tap', target: 'Unknown' }],
    });
    const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-009' });

    // Should NOT contain any auto-generated accessibility identifier
    // The placeholder should use the target name but explicitly mark as draft
    expect(result.code).toContain('DRAFT');
    expect(result.code).toContain('Unknown');
    // Should not fabricate a made-up accessibilityId like "unknown_btn"
    expect(result.code).not.toContain('matching(identifier: "Unknown")');
  });
});

// ─── Test 6: safetyGate handling ───────────────────────────────────

describe('generateDraft — safetyGate', () => {
  it('wraps safetyGate=ask in comment block for XCUITest', () => {
    const flow = makeBasicTapFlow({
      steps: [
        {
          action: 'terminateApp',
          target: 'com.example.app',
          safetyGate: 'ask',
        },
      ],
    });
    const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-010' });

    expect(result.code).toContain('⚠️  SAFETY GATE');
    expect(result.code).toContain('User confirmation required');
  });

  it('wraps safetyGate=ask in comment block for Appium', () => {
    const flow = makeBasicTapFlow({
      steps: [
        {
          action: 'terminateApp',
          target: 'com.example.app',
          safetyGate: 'ask',
        },
      ],
    });
    const result = generateDraft(flow, { format: 'appium', runId: 'run-011' });

    expect(result.code).toContain('⚠️  SAFETY GATE');
    expect(result.code).toContain('User confirmation required');
  });

  it('wraps safetyGate=deny in comment block', () => {
    const flow = makeBasicTapFlow({
      steps: [
        {
          action: 'terminateApp',
          target: 'com.example.app',
          safetyGate: 'deny',
        },
      ],
    });
    const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-012' });

    expect(result.code).toContain('⚠️  SAFETY GATE');
    expect(result.code).toContain('DENIED');
  });
});

// ─── Test 7: Generated code does NOT write to disk ─────────────────

describe('generateDraft — no disk write', () => {
  it('returns only string, does not write to filesystem', () => {
    const flow = makeBasicTapFlow();
    const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-013' });

    // Verify result is a plain object with string code
    expect(typeof result.code).toBe('string');
    expect(result.code.length).toBeGreaterThan(100);
    // filePath only constructs path — does not actually create files
    expect(typeof result.filePath).toBe('string');
    // The file should NOT exist on disk (we never write)
    // We verify by checking no bun file write operations are present in code
  });
});

// ─── Test 8: kebab-to-PascalCase conversion ────────────────────────

describe('generateDraft — PascalCase conversion', () => {
  it('converts kebab-case flowId to PascalCase test class name', () => {
    const flow = makeBasicTapFlow({ flowId: 'user-login-flow' });
    const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-014' });

    expect(result.code).toContain('UserLoginFlowTests');
    // The header naturally contains the flowId; verify the class name uses PascalCase
    expect(result.code).toContain('class UserLoginFlowTests');
    expect(result.code).not.toContain('class user-login-flow');
  });

  it('handles multi-segment kebab-case', () => {
    const flow = makeBasicTapFlow({ flowId: 'deep-link-navigation-test' });
    const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-015' });

    expect(result.code).toContain('DeepLinkNavigationTestTests');
  });

  it('handles single-word flowId', () => {
    const flow = makeBasicTapFlow({ flowId: 'smoke' });
    const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-016' });

    expect(result.code).toContain('SmokeTests');
  });

  it('handles already PascalCase (no change needed)', () => {
    const flow = makeBasicTapFlow({ flowId: 'LoginTest' });
    const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-017' });

    expect(result.code).toContain('LoginTestTests');
  });

  it('uses PascalCase in Appium describe block', () => {
    const flow = makeBasicTapFlow({ flowId: 'login-smoke-test' });
    const result = generateDraft(flow, { format: 'appium', runId: 'run-018' });

    // Appium describe should use PascalCase for the block name
    expect(result.code).toContain("describe('LoginSmokeTest'");
  });
});

// ─── Test 9: Empty steps array throws ──────────────────────────────

describe('generateDraft — empty steps', () => {
  it('throws meaningful error when steps array is empty', () => {
    const flow = makeBasicTapFlow({ steps: [] });

    expect(() => generateDraft(flow, { format: 'xcuitest', runId: 'run-019' })).toThrow(
      'must have at least one step',
    );
  });

  it('throws meaningful error for Appium too', () => {
    const flow = makeBasicTapFlow({ steps: [] });

    expect(() => generateDraft(flow, { format: 'appium', runId: 'run-020' })).toThrow(
      'must have at least one step',
    );
  });
});

// ─── Test 10: Direction mapping for swipe ──────────────────────────

describe('generateDraft — swipe direction mapping', () => {
  it('maps direction up to swipeUp in XCUITest', () => {
    const flow = makeBasicTapFlow({
      steps: [{ action: 'swipe', target: 'List', direction: 'up' }],
    });
    const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-021' });

    expect(result.code).toContain('swipeUp()');
  });

  it('maps direction down to swipeDown in XCUITest', () => {
    const flow = makeBasicTapFlow({
      steps: [{ action: 'swipe', target: 'List', direction: 'down' }],
    });
    const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-022' });

    expect(result.code).toContain('swipeDown()');
  });

  it('maps direction left to swipeLeft in XCUITest', () => {
    const flow = makeBasicTapFlow({
      steps: [{ action: 'swipe', target: 'Carousel', direction: 'left' }],
    });
    const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-023' });

    expect(result.code).toContain('swipeLeft()');
  });

  it('maps direction right to swipeRight in XCUITest', () => {
    const flow = makeBasicTapFlow({
      steps: [{ action: 'swipe', target: 'Carousel', direction: 'right' }],
    });
    const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-024' });

    expect(result.code).toContain('swipeRight()');
  });

  it('maps direction to mobile: swipe in Appium', () => {
    const flow = makeBasicTapFlow({
      steps: [{ action: 'swipe', target: 'List', direction: 'down' }],
    });
    const result = generateDraft(flow, { format: 'appium', runId: 'run-025' });

    expect(result.code).toContain("'mobile: swipe'");
    expect(result.code).toContain("direction: 'down'");
  });
});
