/**
 * Draft Generator — converts FlowV2 objects into XCUITest (Swift) and Appium (TypeScript) test code drafts.
 *
 * Task US-20.1: Test code draft generation.
 *
 * AC1: Generate XCUITest / Appium test code drafts from Flow.
 * AC2: Draft marked as DRAFT, experimental.
 * AC3: Default output to ~/.itestagent/runs/<run_id>/drafts/.
 * AC4: Never auto-commit; user confirms before copying to project.
 *
 * Architecture constraints:
 *   - R5: Never fabricate or guess locator values when locator is undefined/null.
 *   - R7: Never write output files to the project directory.
 *   - R12: All generated code and comments must be in English.
 */
import { homedir } from 'node:os';
import { join } from 'node:path';
import type { FlowStepV2, FlowV2 } from './schema.js';

// ─── Public Types ──────────────────────────────────────────────────

export interface DraftOptions {
  /** Output format: XCUITest (Swift) or Appium (TypeScript) */
  format: 'xcuitest' | 'appium';
  /** Run ID for output path construction */
  runId: string;
}

export interface DraftResult {
  /** Full output file path (not written to disk — R7) */
  filePath: string;
  /** Generated test code string */
  code: string;
  /** Source language of generated code */
  language: 'swift' | 'typescript';
  /** Source flow ID */
  flowId: string;
  /** Run ID */
  runId: string;
}

// ─── Helpers ───────────────────────────────────────────────────────

/**
 * Convert kebab-case string to PascalCase.
 *
 * Examples:
 *   'login-smoke-test' → 'LoginSmokeTest'
 *   'smoke' → 'Smoke'
 *   'LoginTest' → 'LoginTest'
 */
function kebabToPascalCase(input: string): string {
  // First split by kebab/snake/space separators
  const segments = input.split(/[-_\s]+/);

  return segments
    .map((segment) => {
      // Handle already PascalCase segments (e.g. 'LoginTest' → ['Login', 'Test'])
      // Split on uppercase boundaries: 'LoginTest' → ['L', 'ogin', 'T', 'est']
      const camelParts = segment
        .replace(/([A-Z])/g, ' $1')
        .trim()
        .split(/\s+/)
        .filter(Boolean);

      if (camelParts.length > 1) {
        return camelParts.map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()).join('');
      }

      // Single word: just capitalize first letter
      const first = segment.charAt(0).toUpperCase();
      const rest = segment.slice(1).toLowerCase();
      return `${first}${rest}`;
    })
    .join('');
}

/** Generate ISO date string for the current timestamp. */
function isoDateString(): string {
  return new Date()
    .toISOString()
    .replace('T', ' ')
    .replace(/\.\d{3}Z/, '');
}

/** Construct the output file path relative to ~/.itestagent/. */
function buildFilePath(flowId: string, format: 'xcuitest' | 'appium', runId: string): string {
  const ext = format === 'xcuitest' ? '.swift' : '.test.ts';
  return join(homedir(), '.itestagent', 'runs', runId, 'drafts', `${flowId}${ext}`);
}

/** Generate the DRAFT header comment for a language. */
function generateHeader(flowId: string, runId: string, language: 'swift' | 'typescript'): string {
  const comment = language === 'swift' ? '//' : '//';
  const date = isoDateString();
  return [
    `${comment} ⚠️  DRAFT — EXPERIMENTAL — Generated by iTestAgent`,
    `${comment} This is NOT a production test. It is an experimental draft.`,
    `${comment} Review, verify, and adapt before committing to your project.`,
    `${comment} Generated from Flow: ${flowId}`,
    `${comment} Run ID: ${runId}`,
    `${comment} Date: ${date}`,
    '',
  ].join('\n');
}

// ─── Locator Helpers ───────────────────────────────────────────────

/**
 * Build the locator string for a step, or a placeholder comment if missing.
 *
 * R5: Never fabricate or guess locator values. If locator is missing, generate
 * an explicit DRAFT placeholder comment.
 */
function xcuitestLocator(step: FlowStepV2): string {
  if (!step.locator) {
    const target = step.target ?? 'unknown';
    return `// DRAFT: locator missing for "${target}" — TODO: set accessibilityIdentifier in your app`;
  }
  // Use identifier strategy → XCUITest accessibilityIdentifier
  return `app.descendants(matching: .any).matching(identifier: "${step.locator.value}").firstMatch`;
}

function appiumLocator(step: FlowStepV2): string {
  if (!step.locator) {
    const target = step.target ?? 'unknown';
    return `// DRAFT: locator missing for "${target}" — TODO: set accessibilityIdentifier in your app`;
  }
  // Accessibility id selector
  return `await driver.$('~${step.locator.value}')`;
}

// ─── Safety Gate Helpers ───────────────────────────────────────────

function safetyGateComment(
  gate: FlowStepV2['safetyGate'],
  language: 'swift' | 'typescript',
): string {
  const c = '//';
  if (gate === 'ask') {
    return [
      `${c} ⚠️  SAFETY GATE — User confirmation required`,
      `${c} The following step requires explicit user confirmation before execution.`,
      `${c} Remove this guard only after manual review.`,
    ].join('\n');
  }
  if (gate === 'deny') {
    return [
      `${c} ⚠️  SAFETY GATE — DENIED`,
      `${c} The following step was marked as DENIED by the safety gate.`,
      `${c} It is commented out. Do NOT uncomment without explicit authorization.`,
    ].join('\n');
  }
  return '';
}

// ─── Step → XCUITest (Swift) Mapping ───────────────────────────────

function stepToXCUITest(step: FlowStepV2): string {
  const indent = '        ';
  const lines: string[] = [];

  // Wrap with safety gate comment if present
  if (step.safetyGate === 'ask' || step.safetyGate === 'deny') {
    lines.push(safetyGateComment(step.safetyGate, 'swift'));
    lines.push(`${indent}// (commented out for safety)`);
  }

  const prefix = step.safetyGate === 'deny' ? `${indent}// ` : indent;

  switch (step.action) {
    case 'launchApp': {
      const target = step.target ?? 'Unknown App';
      lines.push(`${prefix}// Launch: ${target}`);
      lines.push(`${prefix}app.launch()`);
      break;
    }

    case 'terminateApp': {
      const target = step.target ?? 'Unknown App';
      lines.push(`${prefix}// Terminate: ${target}`);
      lines.push(`${prefix}app.terminate()`);
      break;
    }

    case 'tap': {
      const locatorStr = xcuitestLocator(step);
      lines.push(`${prefix}// Tap: ${step.target ?? 'element'}`);
      if (step.locator) {
        lines.push(
          `${prefix}let el_${step.target?.replace(/[^a-zA-Z0-9]/g, '_') ?? 'target'} = ${locatorStr}`,
        );
        lines.push(`${prefix}el_${step.target?.replace(/[^a-zA-Z0-9]/g, '_') ?? 'target'}.tap()`);
      } else {
        lines.push(`${prefix}${locatorStr}`);
      }
      break;
    }

    case 'longPress': {
      const locatorStr = xcuitestLocator(step);
      const duration = (step.durationMs ?? 1000) / 1000;
      lines.push(`${prefix}// Long press: ${step.target ?? 'element'} (${duration}s)`);
      if (step.locator) {
        lines.push(`${prefix}let lp_el = ${locatorStr}`);
        lines.push(`${prefix}lp_el.press(forDuration: ${duration})`);
      } else {
        lines.push(`${prefix}${locatorStr}`);
        lines.push(`${prefix}// TODO: element.press(forDuration: ${duration})`);
      }
      break;
    }

    case 'swipe': {
      const direction = step.direction ?? 'up';
      const method = `swipe${direction.charAt(0).toUpperCase() + direction.slice(1)}`;
      lines.push(`${prefix}// Swipe ${direction}: ${step.target ?? 'element'}`);
      if (step.locator) {
        lines.push(`${prefix}let sw_el = ${xcuitestLocator(step)}`);
        lines.push(`${prefix}sw_el.${method}()`);
      } else {
        lines.push(`${prefix}// DRAFT: locator missing — app.${method}()`);
      }
      break;
    }

    case 'typeText': {
      const text = String(step.value ?? '');
      lines.push(`${prefix}// Type text: ${step.target ?? 'field'}`);
      if (step.locator) {
        lines.push(`${prefix}let tt_el = ${xcuitestLocator(step)}`);
        lines.push(`${prefix}tt_el.tap()`);
        lines.push(`${prefix}tt_el.typeText("${text}")`);
      } else {
        lines.push(`${prefix}${xcuitestLocator(step)}`);
        lines.push(`${prefix}// TODO: element.typeText("${text}")`);
      }
      break;
    }

    case 'pressButton': {
      const button = String(step.value ?? step.target ?? '').toLowerCase();
      if (button === 'home') {
        lines.push(`${prefix}// Press home button`);
        lines.push(`${prefix}XCUIDevice.shared.press(.home)`);
      } else {
        lines.push(`${prefix}// Press button: ${button}`);
        lines.push(
          `${prefix}// DRAFT: XCUIDevice.shared.press() — unknown button "${button}", review`,
        );
      }
      break;
    }

    case 'openUrl': {
      const url = String(step.value ?? '');
      lines.push(`${prefix}// Open URL: ${url}`);
      lines.push(
        `${prefix}let safari = XCUIApplication(bundleIdentifier: "com.apple.mobilesafari")`,
      );
      lines.push(`${prefix}safari.launch()`);
      lines.push(`${prefix}sleep(1)`);
      lines.push(`${prefix}safari.textFields.firstMatch.tap()`);
      lines.push(`${prefix}safari.textFields.firstMatch.typeText("${url}")`);
      lines.push(`${prefix}safari.buttons["Go"].tap()`);
      break;
    }

    case 'screenshot': {
      lines.push(`${prefix}// Screenshot`);
      lines.push(`${prefix}let screenshot = XCUIScreen.main.screenshot()`);
      lines.push(
        `${prefix}// DRAFT: screenshot captured to memory; add file write logic as needed`,
      );
      break;
    }

    case 'getUiTree': {
      lines.push(`${prefix}// Dump UI tree`);
      lines.push(`${prefix}print(app.debugDescription)`);
      break;
    }

    case 'startRecording': {
      lines.push(`${prefix}// DRAFT: screen recording start not available in XCUITest`);
      lines.push(`${prefix}// Consider using xcrun xctrace or external recording tool`);
      break;
    }

    case 'stopRecording': {
      lines.push(`${prefix}// DRAFT: screen recording stop not available in XCUITest`);
      break;
    }

    case 'collectLogs': {
      lines.push(`${prefix}// DRAFT: log collection not available in XCTest`);
      lines.push(`${prefix}// Use OSLog or external log collection`);
      break;
    }

    case 'assertVisible': {
      lines.push(`${prefix}// Assert visible: ${step.target ?? 'element'}`);
      if (step.locator) {
        lines.push(`${prefix}let av_el = ${xcuitestLocator(step)}`);
        lines.push(
          `${prefix}XCTAssertTrue(av_el.exists, "${step.target ?? 'element'} should be visible")`,
        );
      } else {
        lines.push(`${prefix}${xcuitestLocator(step)}`);
        lines.push(`${prefix}// TODO: XCTAssertTrue(element.exists, "...")`);
      }
      break;
    }

    case 'assertNotVisible': {
      lines.push(`${prefix}// Assert not visible: ${step.target ?? 'element'}`);
      if (step.locator) {
        lines.push(`${prefix}let anv_el = ${xcuitestLocator(step)}`);
        lines.push(
          `${prefix}XCTAssertFalse(anv_el.exists, "${step.target ?? 'element'} should not be visible")`,
        );
      } else {
        lines.push(`${prefix}${xcuitestLocator(step)}`);
        lines.push(`${prefix}// TODO: XCTAssertFalse(element.exists, "...")`);
      }
      break;
    }

    case 'assertText': {
      const expected = step.expectedText ?? '';
      lines.push(`${prefix}// Assert text: "${expected}" on ${step.target ?? 'element'}`);
      if (step.locator) {
        lines.push(`${prefix}let at_el = ${xcuitestLocator(step)}`);
        lines.push(
          `${prefix}XCTAssertEqual(at_el.label, "${expected}", "Text should be '${expected}'")`,
        );
      } else {
        lines.push(`${prefix}${xcuitestLocator(step)}`);
        lines.push(`${prefix}// TODO: XCTAssertEqual(element.label, "${expected}")`);
      }
      break;
    }

    case 'wait': {
      const seconds = (step.durationMs ?? 1000) / 1000;
      lines.push(`${prefix}// Wait ${seconds}s`);
      lines.push(`${prefix}sleep(${seconds})`);
      break;
    }

    case 'comment': {
      const commentText = step.comment ?? '';
      if (commentText.length > 0) {
        lines.push(`${prefix}// ${commentText}`);
      }
      break;
    }

    default:
      // Exhaustive check — should never reach here with TypeScript
      lines.push(`${prefix}// DRAFT: unmapped action "${(step as FlowStepV2).action}"`);
  }

  return lines.join('\n');
}

// ─── Step → Appium (TypeScript) Mapping ────────────────────────────

function stepToAppium(step: FlowStepV2): string {
  const indent = '      ';
  const lines: string[] = [];

  // Wrap with safety gate comment if present
  if (step.safetyGate === 'ask' || step.safetyGate === 'deny') {
    lines.push(safetyGateComment(step.safetyGate, 'typescript'));
    lines.push(`${indent}// (commented out for safety)`);
  }

  const prefix = step.safetyGate === 'deny' ? `${indent}// ` : indent;

  switch (step.action) {
    case 'launchApp': {
      const bundleId = step.target ?? 'com.example.app';
      lines.push(`${prefix}// Launch app: ${bundleId}`);
      lines.push(`${prefix}await driver.activateApp('${bundleId}');`);
      break;
    }

    case 'terminateApp': {
      const bundleId = step.target ?? 'com.example.app';
      lines.push(`${prefix}// Terminate app: ${bundleId}`);
      lines.push(`${prefix}await driver.terminateApp('${bundleId}');`);
      break;
    }

    case 'tap': {
      const locatorStr = appiumLocator(step);
      lines.push(`${prefix}// Tap: ${step.target ?? 'element'}`);
      if (step.locator) {
        const varSuffix = step.target?.replace(/[^a-zA-Z0-9]/g, '_') ?? 'target';
        lines.push(`${prefix}const el_${varSuffix} = ${locatorStr};`);
        lines.push(`${prefix}await el_${varSuffix}.click();`);
      } else {
        lines.push(`${prefix}${locatorStr}`);
      }
      break;
    }

    case 'longPress': {
      const locatorStr = appiumLocator(step);
      const duration = step.durationMs ?? 1000;
      lines.push(`${prefix}// Long press: ${step.target ?? 'element'} (${duration}ms)`);
      if (step.locator) {
        lines.push(`${prefix}const lp_el = ${locatorStr};`);
        lines.push(`${prefix}await lp_el.click({ button: 0, duration: ${duration} });`);
      } else {
        lines.push(`${prefix}${locatorStr}`);
        lines.push(`${prefix}// TODO: element.click({ button: 0, duration: ${duration} });`);
      }
      break;
    }

    case 'swipe': {
      const direction = step.direction ?? 'up';
      lines.push(`${prefix}// Swipe ${direction}: ${step.target ?? 'element'}`);
      lines.push(`${prefix}await driver.execute('mobile: swipe', { direction: '${direction}' });`);
      break;
    }

    case 'typeText': {
      const text = String(step.value ?? '');
      lines.push(`${prefix}// Type text: ${step.target ?? 'field'}`);
      if (step.locator) {
        lines.push(`${prefix}const tt_el = ${appiumLocator(step)};`);
        lines.push(`${prefix}await tt_el.setValue('${text}');`);
      } else {
        lines.push(`${prefix}${appiumLocator(step)}`);
        lines.push(`${prefix}// TODO: element.setValue('${text}');`);
      }
      break;
    }

    case 'pressButton': {
      const button = String(step.value ?? step.target ?? '').toLowerCase();
      if (button === 'home' || button === 'enter') {
        const keyCode = button === 'home' ? 3 : 13;
        lines.push(`${prefix}// Press ${button} button`);
        lines.push(`${prefix}await driver.pressDeviceKey(${keyCode});`);
      } else {
        lines.push(`${prefix}// Press button: ${button}`);
        lines.push(
          `${prefix}// DRAFT: driver.pressDeviceKey() — unknown button "${button}", review key code`,
        );
      }
      break;
    }

    case 'openUrl': {
      const url = String(step.value ?? '');
      lines.push(`${prefix}// Open URL: ${url}`);
      lines.push(`${prefix}await driver.url('${url}');`);
      break;
    }

    case 'screenshot': {
      lines.push(`${prefix}// Screenshot`);
      lines.push(`${prefix}const screenshot = await driver.takeScreenshot();`);
      lines.push(
        `${prefix}// DRAFT: screenshot captured as base64; add file write logic as needed`,
      );
      break;
    }

    case 'getUiTree': {
      lines.push(`${prefix}// Dump UI tree`);
      lines.push(`${prefix}const pageSource = await driver.getPageSource();`);
      break;
    }

    case 'startRecording': {
      lines.push(`${prefix}// Start screen recording`);
      lines.push(`${prefix}// DRAFT: requires Appium screen recording settings to be configured`);
      lines.push(`${prefix}await driver.startRecordingScreen();`);
      break;
    }

    case 'stopRecording': {
      lines.push(`${prefix}// Stop screen recording`);
      lines.push(`${prefix}const recording = await driver.stopRecordingScreen();`);
      break;
    }

    case 'collectLogs': {
      lines.push(`${prefix}// Collect system logs`);
      lines.push(`${prefix}const syslogs = await driver.getLogs('syslog');`);
      break;
    }

    case 'assertVisible': {
      lines.push(`${prefix}// Assert visible: ${step.target ?? 'element'}`);
      if (step.locator) {
        lines.push(`${prefix}const av_el = ${appiumLocator(step)};`);
        lines.push(`${prefix}await expect(av_el).toBeDisplayed();`);
      } else {
        lines.push(`${prefix}${appiumLocator(step)}`);
        lines.push(`${prefix}// TODO: await expect(el).toBeDisplayed();`);
      }
      break;
    }

    case 'assertNotVisible': {
      lines.push(`${prefix}// Assert not visible: ${step.target ?? 'element'}`);
      if (step.locator) {
        lines.push(`${prefix}const anv_el = ${appiumLocator(step)};`);
        lines.push(`${prefix}await expect(anv_el).not.toBeDisplayed();`);
      } else {
        lines.push(`${prefix}${appiumLocator(step)}`);
        lines.push(`${prefix}// TODO: await expect(el).not.toBeDisplayed();`);
      }
      break;
    }

    case 'assertText': {
      const expected = step.expectedText ?? '';
      lines.push(`${prefix}// Assert text: "${expected}" on ${step.target ?? 'element'}`);
      if (step.locator) {
        lines.push(`${prefix}const at_el = ${appiumLocator(step)};`);
        lines.push(`${prefix}await expect(at_el).toHaveText('${expected}');`);
      } else {
        lines.push(`${prefix}${appiumLocator(step)}`);
        lines.push(`${prefix}// TODO: await expect(el).toHaveText('${expected}');`);
      }
      break;
    }

    case 'wait': {
      const duration = step.durationMs ?? 1000;
      lines.push(`${prefix}// Wait ${duration}ms`);
      lines.push(`${prefix}await driver.pause(${duration});`);
      break;
    }

    case 'comment': {
      const commentText = step.comment ?? '';
      if (commentText.length > 0) {
        lines.push(`${prefix}// ${commentText}`);
      }
      break;
    }

    default:
      lines.push(`${prefix}// DRAFT: unmapped action "${(step as FlowStepV2).action}"`);
  }

  return lines.join('\n');
}

// ─── Full File Generators ──────────────────────────────────────────

function generateXCUITestFile(flow: FlowV2, runId: string): string {
  const className = `${kebabToPascalCase(flow.flowId)}Tests`;
  const header = generateHeader(flow.flowId, runId, 'swift');

  const stepsCode = flow.steps.map((step) => stepToXCUITest(step)).join('\n\n');

  return `${header}import XCTest

final class ${className}: XCTestCase {
    var app: XCUIApplication!

    override func setUp() {
        super.setUp()
        continueAfterFailure = false
        app = XCUIApplication()
    }

    override func tearDown() {
        app = nil
        super.tearDown()
    }

    func test_${kebabToPascalCase(flow.flowId)}() {
${stepsCode}
    }
}
`;
}

function generateAppiumTestFile(flow: FlowV2, runId: string): string {
  const describeName = kebabToPascalCase(flow.flowId);
  const header = generateHeader(flow.flowId, runId, 'typescript');

  const stepsCode = flow.steps.map((step) => stepToAppium(step)).join('\n\n');

  return `${header}import { remote } from 'webdriverio';

describe('${describeName}', () => {
  let driver: WebdriverIO.Browser;

  before(async () => {
    // DRAFT: Replace with your actual capabilities
    driver = await remote({
      capabilities: {
        // TODO: Set your desired capabilities here
        platformName: 'iOS',
        'appium:automationName': 'XCUITest',
        'appium:deviceName': 'iPhone Simulator',
        'appium:bundleId': '${flow.steps.find((s) => s.action === 'launchApp')?.target ?? 'com.example.app'}',
      },
    });
  });

  after(async () => {
    if (driver) {
      await driver.deleteSession();
    }
  });

  it('should execute ${describeName}', async () => {
${stepsCode}
  });
});
`;
}

// ─── Public API ─────────────────────────────────────────────────────

/**
 * Generate a test code draft from a FlowV2 object.
 *
 * Converts a validated FlowV2 into either XCUITest (Swift) or Appium (TypeScript/WebDriverIO)
 * test code. The output is a string — no files are written to disk (R7). The filePath
 * in the result is the intended destination path under ~/.itestagent/runs/.
 *
 * @param flow - The validated FlowV2 object to convert
 * @param options - Draft generation options (format, runId)
 * @returns DraftResult with code string and metadata
 * @throws If flow.steps is empty
 *
 * @example
 * ```typescript
 * const result = generateDraft(flow, { format: 'xcuitest', runId: 'run-001' });
 * // result.code contains the Swift test class
 * // result.filePath = '~/.itestagent/runs/run-001/drafts/my-flow.swift'
 * ```
 */
export function generateDraft(flow: FlowV2, options: DraftOptions): DraftResult {
  if (!flow.steps || flow.steps.length === 0) {
    throw new Error('Flow must have at least one step to generate a draft');
  }

  const format = options.format;
  const language = format === 'xcuitest' ? ('swift' as const) : ('typescript' as const);
  const filePath = buildFilePath(flow.flowId, format, options.runId);

  let code: string;
  if (format === 'xcuitest') {
    code = generateXCUITestFile(flow, options.runId);
  } else {
    code = generateAppiumTestFile(flow, options.runId);
  }

  return {
    filePath,
    code,
    language,
    flowId: flow.flowId,
    runId: options.runId,
  };
}
